import { PermissionCode } from '../types.js';
import { WorkflowRole } from '../workflow/types.js';

export const ROLE_CODES: WorkflowRole[] = [
  'ADMIN',
  'INPUTTER',
  'INPUTTER_HO',
  'APPROVER',
  'APPROVER_HO',
  'BRAND',
  'BRAND_MANAGER',
];

export const ROLE_PERMISSION_MATRIX: Record<WorkflowRole, PermissionCode[]> = {
  // System administrator — full access
  ADMIN: [
    'audit.view',
    'channel.view',
    'channel.create',
    'channel.update',
    'category.view',
    'category.create',
    'category.update',
    'location.view',
    'location.create',
    'location.update',
    'content.view',
    'content.create',
    'content.update',
    'content.clone',
    'physical_item.view',
    'physical_item.create',
    'physical_item.update',
    'registration.view',
    'registration.create',
    'registration.update',
    'registration.submit',
    'registration.review',
    'registration.accept',
    'registration.approve',
    'registration.complete',
  ],
  // Branch-level requester — creates and submits registrations
  INPUTTER: [
    'channel.view',
    'category.view',
    'location.view',
    'content.view',
    'content.create',
    'content.update',
    'content.clone',
    'physical_item.view',
    'registration.view',
    'registration.create',
    'registration.update',
    'registration.submit',
  ],
  // Head-office requester — same permissions as INPUTTER
  INPUTTER_HO: [
    'channel.view',
    'category.view',
    'location.view',
    'content.view',
    'content.create',
    'content.update',
    'content.clone',
    'physical_item.view',
    'registration.view',
    'registration.create',
    'registration.update',
    'registration.submit',
  ],
  // Branch management — approves registrations submitted by branch inputters
  APPROVER: [
    'channel.view',
    'category.view',
    'location.view',
    'content.view',
    'physical_item.view',
    'registration.view',
    'registration.review',
    'audit.view',
  ],
  // Head-office management — approves registrations from HO inputters
  APPROVER_HO: [
    'channel.view',
    'category.view',
    'location.view',
    'content.view',
    'physical_item.view',
    'registration.view',
    'registration.review',
    'audit.view',
  ],
  // Brand team — creates/edits master data and handles brand intake step
  BRAND: [
    'audit.view',
    'channel.view',
    'channel.create',
    'channel.update',
    'category.view',
    'category.create',
    'category.update',
    'location.view',
    'location.create',
    'location.update',
    'content.view',
    'content.create',
    'content.update',
    'content.clone',
    'physical_item.view',
    'physical_item.create',
    'physical_item.update',
    'registration.view',
    'registration.create',
    'registration.update',
    'registration.accept',
  ],
  // Brand manager — view-only for master data, gives final registration approval
  BRAND_MANAGER: [
    'audit.view',
    'channel.view',
    'category.view',
    'location.view',
    'content.view',
    'physical_item.view',
    'registration.view',
    'registration.approve',
    'registration.complete',
  ],
};

export const CENTRAL_ROLES = new Set<WorkflowRole>([
  'INPUTTER_HO',
  'APPROVER_HO',
]);
